### ISSUE TITLE
r2s无法云编译

### ISSUE THREAD

**Issue by kevin790565276** [shidahuilang/openwrt#12]
error: failed to push some refs to 'https://github.com/kevin790565276/openwrt'
Error: Process completed with exit code 1.

**Comment by shidahuilang** [comment]
重新fork试试

**Comment by shidahuilang** [comment]
> 错误：无法将一些参考推送到“ https://github.com/kevin790565276/openwrt ” 错误：过程完成，退出代码为 1。

测试了，没有问题

**Comment by kevin790565276** [comment]
谢谢，已经找到问题了

**Comment by kevin790565276** [comment]
编译会超过6个小时被取消怎么解决

**Comment by shidahuilang** [comment]
插件太多，精简一部分，或者选择8370cpu云编译

**Comment by kevin790565276** [comment]
超级加速直接跳过并不会运行，还是在哪里开启？
