### ISSUE TITLE
LEDE luci 版本18.06

### ISSUE THREAD

**Issue by tnwss** [shidahuilang/openwrt#21]
Run cd openwrt

 编译源码: Lede
 源码链接: https://github.com/coolsnowwolf/lede
 源码分支: master
 源码作者: Lede's
 Luci版本: 18.06
 内核版本: 6.1.26
 编译机型: x86-64
 固件作者: shi***
 仓库地址: https://github.com/shi***/openwrt
 启动编号: #103（openwrt仓库第103次启动[Lede-大雕]工作流程）
 编译时间: 2023年05月03号12时14分
 友情提示：您当前使用【Lede】文件夹编译【x[86](https://github.com/shidahuilang/openwrt/actions/runs/4868239525/jobs/8681551370#step:14:87)-64】固件

如果没有记错的话 现在都20多了吧

**Comment by shidahuilang** [comment]
？？什么

**Comment by shidahuilang** [comment]
你可以去大雕那里看看是多少

**Comment by shidahuilang** [comment]
你记错了
