### ISSUE TITLE
++++++++++

### ISSUE THREAD

**Issue by db-one** [shidahuilang/openwrt#22]
++++++

**Comment by shidahuilang** [comment]
> 你个大逗逼，号怎么被扬了，什么水平？ 你个大逗逼，号怎么被扬了，什么水平？ 你个大逗逼，号怎么被扬了，什么水平？ 你个大逗逼，号怎么被扬了，什么水平？ 你个大逗逼，号怎么被扬了，什么水平？ 你个大逗逼，号怎么被扬了，什么水平？ 赶快滚回来

你个吊毛，你个吊毛，你个吊毛，你个吊毛，你个吊毛，你个吊毛，你个吊毛，你个吊毛，你个吊毛，你个吊毛，我要跑路了，回来个毛线

**Comment by db-one** [comment]
> > 你个大逗逼，号怎么被扬了，什么水平？ 你个大逗逼，号怎么被扬了，什么水平？ 你个大逗逼，号怎么被扬了，什么水平？ 你个大逗逼，号怎么被扬了，什么水平？ 你个大逗逼，号怎么被扬了，什么水平？ 你个大逗逼，号怎么被扬了，什么水平？ 赶快滚回来
> 
> 你个吊毛，你个吊毛，你个吊毛，你个吊毛，你个吊毛，你个吊毛，你个吊毛，你个吊毛，你个吊毛，你个吊毛，我要跑路了，回来个毛线

桶提好，别忘记了
