### ISSUE TITLE
主题替换，还有就是能弃用e5编译不，现在你这个7几的u，编译要3个小时

### ISSUE THREAD

**Issue by Namia-Y** [shidahuilang/openwrt#31]
![image](https://github.com/shidahuilang/openwrt/assets/166632307/3e971b03-b940-405e-acf7-29413f6def26)

这个主题没法更换哎，是要我单独去选这个主题嘛？

**Comment by shidahuilang** [comment]
7763是目前最快的 u，主题替换可以去 diy 里面更改

**Comment by shidahuilang** [comment]
主题已经修复

**Comment by shidahuilang** [comment]
主题已经修复，你50个插件，3个小时已经很快了，e5估计都5个多小时了
