### ISSUE TITLE
主题插件麻烦加一下

### ISSUE THREAD

**Issue by Namia-Y** [shidahuilang/openwrt#33]
https://github.com/jerrykuku/luci-app-argon-config

**Comment by shidahuilang** [comment]
不是有吗

**Comment by Namia-Y** [comment]
> 不是有吗
> 
> 

没有吧，我ssh链接选的时候只有你默认的desing-config，没有这个

**Comment by Namia-Y** [comment]
有tg群吗……

**Comment by shidahuilang** [comment]
> > 沒有嗎
> 
> 没有吧，我ssh链接选择的时候你默认的desing-config，没有这个

有了

**Comment by shidahuilang** [comment]
你在看一下，有了

**Comment by shidahuilang** [comment]
> > 没有嗎
> 
> 没有吧，我ssh链接选择的时候你默认的desing-config，没有这个

有了，你看一下

**Comment by shidahuilang** [comment]
> > 没有嗎
> 
> 没有吧，我ssh链接选择的时候你默认的desing-config，没有这个

有了，你看一下

**Comment by Namia-Y** [comment]
> > > 沒有嗎
> 
> > 
> 
> > 没有吧，我ssh链接选择的时候你默认的desing-config，没有这个
> 
> 
> 
> 有了

谢了

**Comment by Namia-Y** [comment]
> > > 沒有嗎
> > 
> > 
> > 没有吧，我ssh链接选择的时候你默认的desing-config，没有这个
> 
> 有了

https://github.com/sirpdboy/NetSpeedTest
你可以看下这个内网测速的插件吗，我自己diy-part.sh无法添加谢谢

**Comment by Namia-Y** [comment]
> 不是有吗
> 
> 

https://github.com/sirpdboy/NetSpeedTest
你可以看下这个内网测速的插件吗，我自己diy-part.sh无法添加谢谢

**Comment by shidahuilang** [comment]
已经添加

**Comment by Namia-Y** [comment]
> 已经添加

![image](https://github.com/shidahuilang/openwrt/assets/166632307/fbf1d296-8fba-4b0c-b91e-3714bfc21b9d)


这个是我这边设置出的问题嘛？

**Comment by Namia-Y** [comment]
> 已经添加



![image](https://github.com/shidahuilang/openwrt/assets/166632307/fbf1d296-8fba-4b0c-b91e-3714bfc21b9d)


这个是我这边设置出的问题嘛？这个五个源码 都出现在这个位子上报错


另一个问题就是，AdGuard 没有自动去创建文件夹编译出来的是这个样子，需要删除此文件才能更行核心我不确定是不是我[diy-part.sh设置出的问题，如果不是请解决下如果是的话我自己解决
![image](https://github.com/shidahuilang/openwrt/assets/166632307/d6c43d31-a1bb-4557-af81-8f4ca3a93821)

如果可以的话你com后端配置的时候可不可把它自带的这个配置删除掉个人觉得这就很鸡肋我自己本来有一套适用于自己的模板，另外哈，个人猜想是不是这个而导致前面无法更新核心。
![image](https://github.com/shidahuilang/openwrt/assets/166632307/e5d7ef37-cc83-4957-a808-a164e0939a4c)


另外luci-app-smartdns缺失

https://github.com/pymumu/smartdns

**Comment by shidahuilang** [comment]
看看你动了什么导致的

**Comment by shidahuilang** [comment]
luci-app-smartdns大雕库里自带就有，所以没必要在拉

**Comment by shidahuilang** [comment]
https://github.com/pymumu/luci-app-smartdns  这个才是，已经添加，自行删除源码自带的

**Comment by shidahuilang** [comment]
https://github.com/pymumu/luci-app-smartdns 这个才是，已经添加

**Comment by shidahuilang** [comment]
https://github.com/pymumu/luci-app-smartdns 这个才是，已经添加，升级最新版本luci和依赖
