### ISSUE TITLE
依赖

### ISSUE THREAD

**Issue by Namia-Y** [shidahuilang/openwrt#34]
又打扰大佬了

天灵源码21.02
WARNING: Makefile 'package/feeds/langge1/linkease/Makefile' has a dependency on 'ffmpeg-remux', which does not exist
WARNING: Makefile 'package/feeds/langge1/luci-app-istorex/Makefile' has a dependency on 'luci-app-store', which does not exist
WARNING: Makefile 'package/feeds/langge1/luci-app-istorex/Makefile' has a dependency on 'luci-lib-taskd', which does not exist
WARNING: Makefile 'package/feeds/langge1/luci-app-quickstart/Makefile' has a dependency on 'luci-app-store', which does not exist
WARNING: Makefile 'package/feeds/langge1/UnblockNeteaseMusic-Go/Makefile' has a build dependency on 'upx/host', which does not exist

Lienol-源码19.07
WARNING: Makefile 'package/feeds/other/automount/Makefile' has a dependency on 'kmod-fs-ntfs3', which does not exist
WARNING: Makefile 'package/feeds/other/nps/Makefile' has a build dependency on 'upx/host', which does not exist
WARNING: Makefile 'package/feeds/passwall3/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/passwall3/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/passwall3/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/passwall3/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/passwall3/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist

Official源码22.03
WARNING: Makefile 'package/feeds/langge1/autocore/Makefile' has a dependency on 'bcm27xx-userland', which does not exist
WARNING: Makefile 'package/feeds/langge1/automount/Makefile' has a dependency on 'kmod-fs-ntfs3', which does not exist
WARNING: Makefile 'package/feeds/packages/bcm27xx-eeprom/Makefile' has a dependency on 'bcm27xx-userland', which does not exist
WARNING: Makefile 'package/feeds/luci/luci-app-cloudflared/Makefile' has a dependency on 'cloudflared', which does not exist
WARNING: Makefile 'package/feeds/passwall3/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/passwall3/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/passwall3/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/passwall3/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist
WARNING: Makefile 'package/feeds/passwall3/shadowsocksr-libev/Makefile' has a dependency on 'libopenssl-legacy', which does not exist

Xwrt-源码
WARNING: Makefile 'package/feeds/luci/luci-app-cloudflared/Makefile' has a dependency on 'cloudflared', which does not exist

以上都是默认分支缺失的依赖，如果你能解决麻烦解决你可以直接看https://github.com/Namia-Y/OpenWrt-X-Beta

这个Lede luci-app测速错误
https://github.com/sirpdboy/netspeedtest/issues/44

Configuring python3-sqlite3.
Collected errors:
 * check_conflicts_for: The following packages conflict with iperf3-ssl:
 * check_conflicts_for: 	iperf3 * 
 * opkg_install_cmd: Cannot install package luci-app-netspeedtest.
 * resolve_conffiles: Existing conffile /Ledemaster/openwrt/build_dir/target-x86_64_musl/root-x86/etc/config/socat is different from the conffile in the new package. The new conffile will be placed at /Ledemaster/openwrt/build_dir/target-x86_64_musl/root-x86/etc/config/socat-opkg.
 * check_conflicts_for: The following packages conflict with iperf3-ssl:

我把sqlite3注释了在编译看看如果你能解决解决下

**Comment by shidahuilang** [comment]
这些都是警告并不影响编译，因为源码种类好几个，有一些插件库和依赖并不是通用的，所以就偷懒了，这个明天看看有时间给搞一下，netspeedtest测速的话如果是iperf3-ssl的话，明天顺手给搞了，因为我一般就用lede的源码编译，其他的都是顺带

**Comment by Namia-Y** [comment]
> 这些都是警告并不影响编译，因为源码种类好几个，有一些插件库和依赖并不是通用的，所以就偷懒了，这个明天看看有时间给搞一下，netspeedtest测速的话如果是iperf3-ssl的话，明天顺手给搞了，因为我一般就用lede的源码编译，其他的都是顺带

感谢另外你符号有错误
![image](https://github.com/shidahuilang/openwrt/assets/166632307/d63e8005-e084-4973-88a9-192dc67628f3)

![image](https://github.com/shidahuilang/openwrt/assets/166632307/fe99c5a8-90d4-44c4-84db-0ab14c070658)

**Comment by Namia-Y** [comment]
> 这些都是警告并不影响编译，因为源码种类好几个，有一些插件库和依赖并不是通用的，所以就偷懒了，这个明天看看有时间给搞一下，netspeedtest测速的话如果是iperf3-ssl的话，明天顺手给搞了，因为我一般就用lede的源码编译，其他的都是顺带

![image](https://github.com/shidahuilang/openwrt/assets/166632307/ddb0fa48-d9d9-4fba-b548-f6dae16c26f1)
zh'ge这个注释掉也是报错
